stages:
  - build
  - deploy

.build-content-base: &build-content-base
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker run -v $(pwd):/content -u `id -u $USER` gitlab-registry.tubit.tu-berlin.de/innodoc/innoconv --verbose --output-dir /content/innoconv_output /content

Build:
  <<: *build-content-base
  except:
    - master
    - legacy-latex

Build (master):
  <<: *build-content-base
  artifacts:
    name: "build-${CI_COMMIT_REF_NAME}"
    paths:
      - innoconv_output/
    expire_in: 1 year
  only:
    - master

Deploy (staging):
  stage: deploy
  image: alpine
  environment: staging
  dependencies:
    - "Build (master)"
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$STAGING_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$STAGING_SERVER_PUBKEY" > ~/.ssh/known_hosts
  script:
    - tar czf - innoconv_output | ssh -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/id_rsa "$STAGING_SERVER_USER"@"$STAGING_SERVER" "$STAGING_DEPLOY_CMD"
  after_script:
    - rm -f ~/.ssh/id_rsa
  only:
    - master
